# backend: Specifies how to connect to your content.
# We're using GitHub, so you need to provide your repository details.
# Replace YOUR_USERNAME/YOUR_REPOSITORY_NAME with your actual repo path.
backend:
  name: github
  repo: Racej255/crossland
  branch: main # Or master, depending on your repository's default branch

# media_folder: Where to upload and store images and other media files.
media_folder: "gallery"
public_folder: "/gallery"

# collections: Defines the different types of content on your site.
# This is a "file collection", for editing specific pages.
collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "Home Page"
        file: "_data/home.yml"
        description: "Content for the main homepage."
        fields:
          - { label: "Page Title", name: "title", widget: "string" }
          - { label: "Page Subtitle", name: "subtitle", widget: "string" }
          - { label: "Main Quote", name: "quote", widget: "text" }
          - { label: "Quote Author", name: "quote_author", widget: "string" }
          - label: "Upcoming Events (Sidebar)"
            name: "events"
            widget: "list"
            fields:
              - { label: "Event Date", name: "date", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
          - label: "House Members"
            name: "members"
            widget: "list"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Portrait Image", name: "image", widget: "image" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Role", name: "role", widget: "string" }
          - label: "Past Members"
            name: "past_members"
            widget: "list"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Portrait Image", name: "image", widget: "image" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Status", name: "status", widget: "string" }
          - { label: "Full History", name: "history", widget: "markdown" }

      - name: "gala"
        label: "Gala Page"
        file: "_data/gala.yml"
        description: "Content for the Grand Crossland Gala page."
        fields:
          - { label: "Page Title", name: "title", widget: "string" }
          - { label: "Page Subtitle", name: "subtitle", widget: "string" }
          - { label: "Introduction", name: "introduction", widget: "markdown" }
          - { label: "Date", name: "date", widget: "string" }
          - { label: "Time", name: "time", widget: "string" }
          - { label: "Location", name: "location", widget: "string" }
          - label: "Event Schedule"
            name: "schedule"
            widget: "list"
            fields:
              - { label: "Time", name: "time", widget: "string" }
              - { label: "Activity", name: "activity", widget: "string" }
          - label: "Standard Menu"
            name: "standard_menu"
            widget: "list"
            field: { label: "Menu Item", name: "item", widget: "string" }
          - label: "Vegetarian Menu"
            name: "vegetarian_menu"
            widget: "list"
            field: { label: "Menu Item", name: "item", widget: "string" }
          - { label: "Costs & Payment Info", name: "payment_info", widget: "markdown" }
          - label: "Testimonials"
            name: "testimonials"
            widget: "list"
            fields:
              - { label: "Quote", name: "quote", widget: "text" }
              - { label: "Author", name: "author", widget: "string" }
          - label: "Gallery Images"
            name: "gallery"
            widget: "list"
            summary: "{{fields.image}}"
            field: { label: "Image", name: "image", widget: "image"}
